function updateSpeciesDataTable(vObj)

set(vObj.h.SpeciesDataTable,...    
    'ColumnName',{'Species','# Tasks per Species','Data','f(x)','ObjectiveFcn'},...
    'ColumnEditable',[true false true true true],...
    'ColumnFormat',{vObj.SpeciesPopupTableItems(:),'float',vObj.PrunedDatasetHeader(:),'char',vObj.ObjectiveFunctions(:)});
