function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - The MyPackageViewer.Empty vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2014-2015 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: rjackey $
%   $Revision: 282 $  $Date: 2016-09-01 10:04:43 -0400 (Thu, 01 Sep 2016) $
% ---------------------------------------------------------------------

TitleColor = [0.6235    0.7255    0.8314];

%% Main Panel and layout

vObj.h.SessionPanel = uix.BoxPanel(...
    'Parent',vObj.UIContainer,...
    'FontSize',10,...
    'Title','Session',...
    'TitleColor',TitleColor);

vObj.h.SessionLayout = uix.VBox(...
    'Parent',vObj.h.SessionPanel,...
    'Padding',10,...
    'Spacing',12);

vObj.h.SettingsLayout = uix.Grid(...
    'Parent',vObj.h.SessionLayout,...
    'Padding',10,...
    'Spacing',10);

vObj.h.AutoSavePanel = uix.Panel(...
    'Parent',vObj.h.SessionLayout,...
    'Title','Auto-Save Settings',...
    'FontSize',10,...
    'FontWeight','bold',...
    'Padding',10);
vObj.h.AutoSaveLayout = uix.Grid(...
    'Parent',vObj.h.AutoSavePanel,...
    'Padding',10,...
    'Spacing',10);

vObj.h.SessionLayout.Heights = [150 -1];


%% Directory Selectors

% Labels

vObj.h.RootDirLabel = uicontrol(...
    'Parent',vObj.h.SettingsLayout,...
    'Style','text',...
    'String','Root Directory:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

vObj.h.ObjectiveFunctionsDirLabel = uicontrol(...
    'Parent',vObj.h.SettingsLayout,...
    'Style','text',...
    'String','Objective Functions Directory:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

vObj.h.CustomFunctionsDirLabel = uicontrol(...
    'Parent',vObj.h.SettingsLayout,...
    'Style','text',...
    'String','User-defined Functions Directory:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

vObj.h.AutoSaveLabel = uicontrol(...
    'Parent',vObj.h.SettingsLayout,...
    'Style','text',...
    'String','Use Auto-Save:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');


% Selectors

vObj.h.RootDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.SettingsLayout,...
    'Value', '', ...
    'Title', 'Select the root directory', ...
    'Tag', 'RootDirectory', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onFileSelection(vObj,h,e) );

vObj.h.ObjectiveFunctionsDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.SettingsLayout,...
    'Value', '', ...
    'Title', 'Select the objective functions directory', ...
    'Tag', 'RelativeObjectiveFunctionsPath', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onFileSelection(vObj,h,e) );

vObj.h.UserDefinedFunctionsDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.SettingsLayout,...
    'Value', '', ...
    'Title', 'Select the user-defined functions directory', ...
    'Tag', 'RelativeUserDefinedFunctionsPath', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onUDFSelection(vObj,h,e) );

vObj.h.AutoSaveCheckbox = matlab.ui.control.UIControl( ...
    'Parent',vObj.h.SettingsLayout,...
    'Style','checkbox', ...
    'FontSize',10,...
    'String','',...
    'Callback',@(h,e)onAutoSaveChecked(vObj,h,e));

% Sizes
vObj.h.SettingsLayout.Heights = [25 25 25 25];
vObj.h.SettingsLayout.Widths = [250 -1];


%% Auto-Save Settings

% Labels

vObj.h.AutoSaveDirLabel = uicontrol(...
    'Parent',vObj.h.AutoSaveLayout,...
    'Style','text',...
    'String','Directory:',...
    'FontSize',10,...
    'HorizontalAlignment','left');

vObj.h.AutoSaveFrequencyLabel = uicontrol(...
    'Parent',vObj.h.AutoSaveLayout,...
    'Style','text',...
    'String','Frequency (min):',...
    'FontSize',10,...
    'HorizontalAlignment','left');

vObj.h.AutoSaveBeforeRunLabel = uicontrol(...
    'Parent',vObj.h.AutoSaveLayout,...
    'Style','text',...
    'String','Before Run:',...
    'FontSize',10,...
    'HorizontalAlignment','left');

% Selectors

vObj.h.AutoSaveDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.AutoSaveLayout,...
    'Value','', ...
    'Title','Select the auto-save directory', ...
    'Tag','RelativeAutoSavePath', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onFileSelection(vObj,h,e) );

vObj.h.AutoSaveFrequencyEdit = uicontrol(...
    'Parent',vObj.h.AutoSaveLayout,...
    'Style','edit',...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'Callback',@(h,e)onAutoSaveFrequencyEdited(vObj,h,e));
            
vObj.h.AutoSaveBeforeRunCheckbox = matlab.ui.control.UIControl( ...
    'Parent',vObj.h.AutoSaveLayout,...
    'Style','checkbox', ...
    'FontSize',10,...
    'String','',...
    'Callback',@(h,e)onAutoSaveBeforeRunChecked(vObj,h,e));

% Sizes
vObj.h.AutoSaveLayout.Heights = [25 25 25];
vObj.h.AutoSaveLayout.Widths = [250 -1];