function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - The MyPackageViewer.Empty vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2014-2015 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: rjackey $
%   $Revision: 282 $  $Date: 2016-09-01 10:04:43 -0400 (Thu, 01 Sep 2016) $
% ---------------------------------------------------------------------

TitleColor = [0.6235    0.7255    0.8314];

%% Main Panel and layout

vObj.h.SessionPanel = uix.BoxPanel(...
    'Parent',vObj.UIContainer,...
    'FontSize',10,...
    'Title','Session',...
    'TitleColor',TitleColor);

vObj.h.SessionLayout = uix.Grid(...
    'Parent',vObj.h.SessionPanel,...
    'Padding',5,...
    'Spacing',10);


%% Directory Selectors

% Labels

vObj.h.RootDirLabel = uicontrol(...
    'Parent',vObj.h.SessionLayout,...
    'Style','text',...
    'String','Root Directory:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');


vObj.h.ResultsDirLabel = uicontrol(...
    'Parent',vObj.h.SessionLayout,...
    'Style','text',...
    'String','Results Directory:',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');


% vObj.h.ObjectiveFunctionsDirLabel = uicontrol(...
%     'Parent',vObj.h.SessionLayout,...
%     'Style','text',...
%     'String','Functions Directory:',...
%     'FontSize',10,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');



% Selectors

vObj.h.RootDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.SessionLayout,...
    'Value', '', ...
    'Title', 'Select the root directory', ...
    'Tag', 'RootDirectory', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onFileSelection(vObj,h,e) );

vObj.h.ResultsDirSelector = uix.widget.FolderSelector(...
    'Parent',vObj.h.SessionLayout,...
    'Value', '', ...
    'Title', 'Select the results directory', ...
    'Tag', 'RelativeResultsPath', ... %the field the result goes in Session
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onFileSelection(vObj,h,e) );

% vObj.h.FunctionsDirSelector = uix.widget.FolderSelector(...
%     'Parent',vObj.h.SessionLayout,...
%     'Value', '', ...
%     'Title', 'Select the additional functions directory', ...
%     'Tag', 'RelativeFunctionsPath', ... %the field the result goes in Session
%     'HorizontalAlignment', 'left',...
%     'InvalidForegroundColor',[1 0 0],...
%     'Callback',@(h,e)onFileSelection(vObj,h,e) );

% Sizes
vObj.h.SessionLayout.Heights = [25 25];
vObj.h.SessionLayout.Widths = [120 -1];

