classdef gQSPSimTester < QSPViewer.App
    methods
        function obj = gQSPSimTester(filename)
            if nargin == 0
                rootDirectory = string(pwd) + "/../Sessions/CaseStudy_aPCSK9/aPCSK9_v7_MES_complete/";;
                filename = rootDirectory + "CaseStudy2_aPCSK9.qsp.mat";
            else
                rootDirectory = fileparts(filename);
            end
            
            a = obj.loadSessionFromFile(filename, false);
            obj.Session.RootDirectory = char(rootDirectory);
            obj.Session.UseParallel = false;
            obj.Session.AutoSaveBeforeRun = false;
        end
        
        function testCase = runSimulations(obj, testCase)
            for i = 1:numel(obj.Session.Simulation)
                simResultsFolder = string(obj.Session.Simulation(i).SimResultsFolderName);
                obj.Session.Simulation(i).SimResultsFolderName = 'tmp';
                
                [a, e] = obj.Session.Simulation(i).run;
                
                % This assumes an empty "current" directory for output. So
                % any new files found here are those generated by the
                % Simulation and are used for comparison. If there is a
                % failure the actual files that fail are copied into a
                % failed directory in order to facilitate debugging.
                p = string(obj.Session.RootDirectory) + "/tmp";
                d = dir(p + "/*.mat");
                for result_i = 1:numel(d)
                    actualName = [d(result_i).folder, '/', d(result_i).name];
                    
                    actual = load(actualName);
                    
                    % optimize getting this directory listing..
                    expectedResults = dir(obj.Session.RootDirectory + "/" + simResultsFolder);
                    expectedFileNames = string({expectedResults.name});
                    currentFile = string(d(result_i).name);
                    currentFile = currentFile.extractBefore("Date = ");
                    
                    expectedEntryTF = expectedFileNames.contains(currentFile);
                    expectedFile = expectedResults(expectedEntryTF);
                    expected = load(expectedFile.folder + "/" + expectedFile.name);
                    
                    testCase.verifyEqual(actual, expected, 'RelTol', 1e-2, 'AbsTol', 1e-4);
                    
                    % Cleanup TODO. If the test failed move the generated
                    % data to a failed directory to aid debugging. Else we
                    % delete the generated file.
                    delete(actualName);
                end
            end
        end
        
        function runOptimizations(obj)
            for i = 1:numel(obj.Session.Optimization)
                [a, e] = obj.Session.Optimization(i);
            end
        end
    end
end