function updateSpeciesDataTable(vObj)

set(vObj.h.SpeciesDataTable,...    
    'ColumnName',{'Species','# Tasks per Species','Data','f(x)'},...
    'ColumnEditable',[true false true true],...
    'ColumnFormat',{vObj.SpeciesPopupTableItems(:),'float',vObj.DatasetDataColumn(:),'char'});
