function updateSpeciesDataTable(vObj)

set(vObj.h.SpeciesDataTable,...    
    'ColumnName',{'Species (x)','# Tasks per Species','y=f(x)','Data (y)'},...
    'ColumnEditable',[true false true true],...
    'ColumnFormat',{vObj.SpeciesPopupTableItems(:),'float','char',vObj.DatasetDataColumn(:)});
