function updateItemsTable(vObj)

% Set the data
set(vObj.h.ItemsTable,...
    'ColumnEditable',[true true true],...
    'ColumnName',{'Task','Group','Virtual Population'},...
    'ColumnFormat',{vObj.TaskPopupTableItems(:), ... vObj.GroupPopupTableItems(:),
        'char', vObj.VPopPopupTableItems(:)});
