function updateItemsTable(vObj)

% Set the data
set(vObj.h.ItemsTable,...
    'ColumnEditable',[true true true],...
    'ColumnName',{'Task','Virtual Population','Virtual Patient Group to Simulate','Available Groups in Virtual Patients',},...
    'ColumnFormat',{vObj.TaskPopupTableItems(:), ... vObj.GroupPopupTableItems(:),
        vObj.VPopPopupTableItems(:), 'char', 'char'});
